### ISSUE TITLE
Consider replacing pyparsing with something better

### ISSUE THREAD

**Issue by michaelpirrello** [synrg/dronefly#106]
Per discussion.

**Comment by synrg** [comment]
My complaints here are:

- utf8 handling is poor (huge performance hit so we only handle a reduced subset suitable for users of latin alphabet based writing systems)
- overkill for what we need (our grammar isn't that complex)
- stifles further grammar development because it's a pain to deal with

**Comment by synrg** [comment]
I think a standard argument parser (a la unix command-line argument parser) would work here, except matching any keywords in the query (excluding stuff inside double-quotes) and prefixing them with `--` to make them into options. Thus:

`,t prunella in plants by me` -> `,t prunella --in plants --by me`

That's essentially the approach suggested here in the accepted solution to this question:

<https://stackoverflow.com/questions/11310626/python-argparse-optional-arguments-without-dashes>

**Comment by synrg** [comment]
Closed by 2e0f00181280d5ed2ce561a273c9be903985b87d.
