### ISSUE TITLE
Build out operator/subcommands for my alias, e.g. ,my <X>

### ISSUE THREAD

**Issue by michaelpirrello** [synrg/dronefly#109]
"<X> = Big 6 - Observations, Identifications, Taxa, People, Places, Projects
<subX> = photos, sounds, flags, etc.

**Comment by synrg** [comment]
Rather large and vaguely defined. Probably warrants a separate issue per `my <x>` supported.

**Comment by synrg** [comment]
Deliberately not labeling this with any of the big 6. This is just a reminder to put more under `my`, with an issue filed per thing (and they can be labelled as such).

**Comment by synrg** [comment]
This is not a directly actionable issue. We're beginning to incorporate more `,my` plans into new issues like #129 so there is no need to have this issue anymore. As indicated in my previous comment, if we have any specific ideas for `,my` as an alias, please file an issue per specific feature request.
