### ISSUE TITLE
iNat "heartbeat" monitor

### ISSUE THREAD

**Issue by michaelpirrello** [synrg/dronefly#121]
Consider monitoring the status of the iNaturalist site through a "heartbeat" API call like https://api.inaturalist.org/v1/observations?per_page=0

As discussed, monitor total results for change, and express as
Soft Outage: No change in number across two API calls
Hard Outage: Error or no result returned

Post status changes to a channel like #inat-posts (or in an embed, perhaps in #welcome ?)

**Comment by synrg** [comment]
I honestly don't feel this is a good fit for inatcog. It might make an interesting cog of its own, though, but I'm not going to write it.
