### ISSUE TITLE
Implement use of ...during 

### ISSUE THREAD

**Issue by michaelpirrello** [synrg/dronefly#131]
As discussed in #research-and-tech, add support for ...during (e.g. ,tab life not by me from william penn state forest during aug, sep). This should also accomplish feature parity with the Months dropdown in the Date Observed portion of the filter:
![image](https://user-images.githubusercontent.com/63756824/91462442-2b555480-e858-11ea-8fa6-cc0e80df7135.png)

**Comment by synrg** [comment]
The desired result is currently possible with `opt month=7,8`.
