### ISSUE TITLE
inatcog: provide map image in command response

### ISSUE THREAD

**Issue by synrg** [synrg/dronefly#19]
For some commands, it may make sense to provide a map image in the command response as well as a link to the web for closer inspection. A map directly output in channel could convey the information more efficiently to a group of people than having each person click the link.

While Discord has no direct support for Google maps, here's a plan to support it:

- Provide a separate *inatmaps* cog that enhances existing inat commands with map images.
- This cog can use the python selenium package and chromedriver to get the map images.
- I tried a proof of principle exercise in the python interpreter and it's not much code at all to get the screenshot. Performance, even on my tiny Atom-based home server, was acceptable.
- Once the screenshot is taken, it just needs to be uploaded so the Discord embed can use it, also not difficult code.

See also #18 which could benefit from this.

**Comment by synrg** [comment]
This would be more reasonably accomplished using the API, retrieving tiles and assembling them into an image that is uploaded to Discord.

**Comment by michaelpirrello** [comment]
Potentially expensive task that wouldn't necessarily provide a better result than the web (no ability to use layers) and would take significant vertical screen space to be large enough to be useful given present interface.

**Comment by synrg** [comment]
What might change my mind on this one is if Discord coughs up the user interface changes soon that allow us to build features like this in a useful way (i.e. if the map were interactive, not static, then we'd have something!) I'm going to go ahead and close the issue since it's not immediately actionable. If things change, we can always reopen it again later.
