### ISSUE TITLE
obs (grammar): support unknown & any as concepts

### ISSUE THREAD

**Issue by synrg** [synrg/dronefly#89]
## unknown

In a `[p]taxon` query, `unknown` should take you to a synthetic taxon embed with the iNat icon as its thumbnail and the count should be only for `iconic_taxa=unknown` (i.e. iNaturalist has no page for this taxon, hence synthetic).

In a `[p]obs` query or any other context where observations are searched (e.g. obs/spp# counts or the link to total# observations for the taxon) always search for `iconic_taxon=unknown` if `unknown` was specified in the query.

## any

In a `[p]taxon` query, `any` should mean all observations on iNat, e.g. at time of writing this issue, `http://api.inaturalist.org/v1/observations?per_page=0&verifiable=any` => `{"total_results":40009286,"page":1,"per_page":0,"results":[]}`. So again, this should be a synthetic taxon embed.

Similarly, in a `[p]obs` query, the search just won't include any terms at all (unless a filter was applied)

## Filters

Filters should by applied as usual, e.g. `[p]obs any from canada by me` should include any observations (life or unknown) from the user typing the command, and add their counts to the user counts table.

## Keyword only valid when typed by itself

Because `any` or `unknown` could be part of a query, consider if they should only be treated as keywords when typed by itself, i.e. not with other search terms, rank keywords, or part of a compound query, e.g. in these contexts, treat it as an ordinary word. The only time other words may be used is with filters that make sense to combine with them like `by` and `from`.

`[p]taxon unknown in animals` -> *Leucania incognita* (Unknown Wainscot)
`[p]taxon any in plants` -> Genus *Paronychia* (Anychia)
`[p]taxon family any` -> Family Anyphaenidae (Ghost Spiders)

That is, all of the current behaviours of these searches should be preserved.

**Comment by synrg** [comment]
@michaelpirrello relating to your comment on #91 :

I assume you mean you'd like to be able to search bacteria, archaea and viruses with some other name that doesn't mess up existing searches. `,obs bacteria by me` should currently return only Kingdom Bacteria. It would be wrong to make it also include archaea and viruses.

I'm all for typing aids, but I'm hesitant to make paraphyletic groupings that reinforce concepts outside of the iNat taxonomy. If we were to go in this direction, I'd want clear visual indicators that the grouping is invented for convenience and not an actual taxonomic grouping in the hierarchy.

But to get to the heart of the matter, why these three? In a conversation elsewhere with you, you said "if for no other reason than to eliminate the need to specifically exclude those when doing an iconic taxon search for unknowns". That seems like a workaround for a specific bug in the search form, that "iconic_taxa=unknown" actually matches these accidentally.

So addressing that issue head-on, what if we alter the meaning of the keyword 'unknown' to specifically mean iconic_taxa=unknown&without_taxon_id=67333,151817,131236?

**Comment by michaelpirrello** [comment]
As discussed, I'm good with that.

**Comment by synrg** [comment]
The `any` concept is supported in `,obs` and `,s obs` now by simply omitting any taxon keywords from the query. I don't think `any` as a concept for `taxon` commands makes sense, though. So I don't know if we need to support `any` as a keyword now. I am still in support of eventually implementing the `unknown` part of this request, but it isn't as high on my current list of priorities as many other issues in the system.

**Comment by synrg** [comment]
The `unknown` concept is now supported across `,search obs`, `,obs`, and `,tab` commands as per the refined definition above. Since we have scrapped the `any` idea because it is implicit in the commands where it would've been useful when you haven't provided a taxon, this feature is now complete.
